# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nycTrees' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  # Pods for nycTrees

  target 'nycTreesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nycTreesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
